apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: transcripter
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: ml-backend
    app.kubernetes.io/part-of: transcripter
spec:
  replicas: 1
  strategy:
    type: Recreate # Needed for persistent storage
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/component: ml-backend
        app.kubernetes.io/part-of: transcripter
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          name: http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: transcripter
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: ml-backend
    app.kubernetes.io/part-of: transcripter
spec:
  selector:
    app.kubernetes.io/name: ollama
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    protocol: TCP
  type: ClusterIP
