apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcripter-app
  namespace: transcripter
  labels:
    app.kubernetes.io/name: transcripter-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: transcripter
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: transcripter-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transcripter-app
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: transcripter
    spec:
      containers:
      - name: transcripter
        image: transcripter:latest
        ports:
        - containerPort: 7860
          name: http
        envFrom:
        - configMapRef:
            name: transcripter-config
        - secretRef:
            name: transcripter-secrets
            optional: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: transcripter-service
  namespace: transcripter
  labels:
    app.kubernetes.io/name: transcripter-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: transcripter
spec:
  selector:
    app.kubernetes.io/name: transcripter-app
  ports:
  - name: http
    port: 80
    targetPort: 7860
    protocol: TCP
  type: ClusterIP
