apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: transcripter-staging

resources:
- ../../base

patchesStrategicMerge:
- staging-patches.yaml

images:
- name: transcripter
  newName: registry.digitalocean.com/your-registry/transcripter
  newTag: staging

configMapGenerator:
- name: transcripter-config
  behavior: merge
  literals:
  - LOG_LEVEL=DEBUG
  - MAX_CONCURRENT_REQUESTS=2

replicas:
- name: transcripter-app
  count: 1
- name: ollama
  count: 1

commonLabels:
  environment: staging

nameSuffix: "-staging"
